In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd; pd.set_option("display.max_columns", None)
import sys;sys.path.append("..")
from config import Paths
from dataframes import *
from eals_data.utils import venn_diagram
from eals_radcliff.utils import dataframes as radcliff_dataframes
from eals_radcliff.utils import dataframes_paper as radcliff_dataframes_paper

# ALSFRS-R

In [3]:
df_als = load_alsfrsr_data()
print(f'N pALS: {df_als.user_id.nunique()}, N sessions: {df_als.session_id.nunique()}')
df_als.head(2)

FileNotFoundError: [Errno 2] No such file or directory: '/data-output/s3_rapa/demographics/RAPA EAP ALSFRS Data.csv'

In [ ]:
# Only one pALS in common between RAPA and Radcliff ALSFRS-R datasets

df_als_radcliff = radcliff_dataframes.load_alsfrsr_data()

venn_diagram(df_als.user_id.unique(), df_als_radcliff.user_id.unique())

(10, 1, 69)

# Demographics

In [ ]:
df_demo = load_demographics_data()
print(f'N pALS: {df_demo.user_id.nunique()}, N sessions: {df_demo.session_id.nunique()}')
df_demo.head(2)

N pALS: 15, N sessions: 24

,user_id,family_disease_details,adhd_add,als,anxiety,bipolar_disorder,brain_aneurysm,Bulbar,c9orf_mutation,cancer,residence_location,birth_location,clinic_city,clinic_name,cognitive_impairment,concussions,consent_signed,date_of_birth,date_of_diagnosis,symptom_onset_date,dementia,depression,diabetes,diagnosis,Do You Use The Railing When Climbing Stairs?,additional_conditions,current_cold,family_neuro_history,stairs_at_home,epilepsy,ethnicity,hearing_loss,recent_hospitalization,speech_therapy,recent_quit_smoking,height_feet,height_inch,education_level,stairs_description,number_of_steps,english_first_language,symptom_onset_site_limb,marital_status,muscle_disease,No,birth_gender,specific_allergies,step_height,race,residence_type,residence_type_2,schizophrenia,symptom_onset_site,smoking_history,household_income,weight,current_prescriptions,stairs_flooring,dominant_hand,occupation,orthotics_type,study_shoes_type,us_region_identity,neurologist_physician_name,other_education,other language,other_symptoms,date,height_in_m,weight_in_kg,bmi,age,years_since_onset,session_id
0,1b0b349e-301f-46a4-a137-1fed70ca678d,NaN,No,Known ALS Gene,No,No,No,Swallowing,No,No,"Tustin, California",Mexico,Orange,UCI,No,No,Yes,1979-07-03,12/05/2024,2023-08-01,No,No,No,ALS,NaN,None of the above,No,NaN,NaN,No,"Mexican, Mexican American, Chicano/a",No,No,"yes, not currently",No,5,5,High School,NaN,NaN,No,NaN,Single,No,Spanish,Female,[],NaN,White,NaN,Condo/townhouse,No,Bulbar,I have never smoked,NaN,148,[],NaN,Right,"Disability, Not working at this time",[],NaN,West,Dr. Jeffery Mullen,NaN,NaN,NaN,2025-05-22,1.651,67.131616,24.628216,46,1.806982,1b0b349e-301f-46a4-a137-1fed70ca678d__2025-05-22
1,1b0b349e-301f-46a4-a137-1fed70ca678d,NaN,No,Known ALS Gene,No,No,No,Swallowing,No,No,"Tustin, California",Mexico,Orange,UCI,No,No,Yes,1979-07-03,12/05/2024,2023-08-01,No,No,No,ALS,NaN,None of the above,No,NaN,NaN,No,"Mexican, Mexican American, Chicano/a",No,No,"yes, not currently",No,5,5,High School,NaN,NaN,No,NaN,Single,No,Spanish,Female,[],NaN,White,NaN,Condo/townhouse,No,Bulbar,I have never smoked,NaN,148,[],NaN,Right,"Disability, Not working at this time",[],NaN,West,Dr. Jeffery Mullen,NaN,NaN,NaN,2025-07-10,1.651,67.131616,24.628216,46,1.941136,1b0b349e-301f-46a4-a137-1fed70ca678d__2025-07-10

In [ ]:
# No pALS in common between RAPA and Radcliff Demographics datasets

df_demo_radcliff = radcliff_dataframes.load_demographics_data()

venn_diagram(df_demo.user_id.unique(), df_demo_radcliff.user_id.unique())

(15, 0, 78)

# ROADS

In [ ]:
df_roads = load_roads_data()
print(f'N pALS: {df_roads.user_id.nunique()}, N sessions: {df_roads.session_id.nunique()}')
df_roads.head(2)

N pALS: 11, N sessions: 88

,nod_yes_and_no,ride_in_a_car,eat_soup,drink_milkshake,sit_on_toilet,swallow_pills,blow_out_candle,eat_dry_food,speak_on_phone,drink_out_of_glass,eat_large_meal,sign_nam_proper,get_into_bed,roll_over_in_bed,take_shower,use_knife_and_fork,walk_around_your_home,move_a_chair,speak_in_load_room,speak_for_hours,clip_nails,walk_up_1_flight_of_stairs,walk_up_a_hill,climb_a_stepstool,give_up_from_the_floor,carry_an_object_downstairs,stand_for_hours,get_heavy_objects_off_high_shelf,total,date_created,user_id,date,session_id
0,2,2,2,2,2,2,2,2,2,2,2,1,2,1,1,1,1,0,2,2,1,0,0,0,0,0,0,0,34,2025-07-10T20:30:01.000Z,a07848cb-83b1-48ef-a314-ae5b5e5d448b,2025-07-10,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2025-07-10
1,2,2,2,2,2,2,2,2,2,2,2,1,2,1,1,1,1,0,2,2,1,0,0,0,0,0,0,0,34,2025-06-12T16:28:10.000Z,a07848cb-83b1-48ef-a314-ae5b5e5d448b,2025-06-12,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2025-06-12

# ZephyrX

In [ ]:
df_zx = load_zephyrx_data()

1 - ORIGINAL DIMENSIONS:                           subjects:      2, sessions:     52, spiro:    147, cols: 108
2 - AFTER PULMONOLOGIST (2023-03-01):              subjects:      2, sessions:     52, spiro:    147, cols: 108
3 - CRITERIA: n_fvc_atleast_usable >= 2 or vc > 0  subjects:      2, sessions:     52, spiro:    121, cols: 109
--- WARNING computing 'total_timespan' for each user after usability criteria: True
--- TOTAL TIMESPAN: min 412, max 454, mean 433.52
4 - MORE THAN 2 MONTHS IN STUDY                    subjects:      2, sessions:     52, spiro:    121, cols: 110
5 - SUBJECTS MORE THAN 6 SESSIONS pftType          subjects:      2, sessions:     52, spiro:    121, cols: 111

/home/ubuntu/git/eals_rapa/nb/../dataframes.py:380: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  )

In [ ]:
# No pALS in common

df_zx_radcliff = radcliff_dataframes_paper.load_zephyrx_data_paper()

venn_diagram(df_zx.user_id.unique(), df_zx_radcliff.subject_id.unique())

1 - ORIGINAL DIMENSIONS:                           subjects:     74, sessions:   1552, spiro:   3874, cols: 109
2 - EXCLUDING ANY OF 46 TEST USERS:                subjects:     74, sessions:   1552, spiro:   3874, cols: 109
3 - EXCLUDING ONLY ZX SESSIONS:                    subjects:     73, sessions:   1477, spiro:   3655, cols: 109
4 - AFTER PULMONOLOGIST (2023-03-01):              subjects:     70, sessions:   1397, spiro:   3486, cols: 109
ALL_SESSIONS is None. Loading...
load_all_sessions took 0.07
5 - ONLY AT REST SPIROMETRIES:                     subjects:     44, sessions:   1189, spiro:   1924, cols: 109
6 - CRITERIA: n_fvc_atleast_usable >= 2 or vc > 0  subjects:     44, sessions:   1189, spiro:   1924, cols: 110
--- WARNING computing 'total_timespan' for each patient after usability criteria: True
--- TOTAL TIMESPAN: min 0, max 728, mean 421.15
7 - MORE THAN 2 MONTHS IN STUDY                    subjects:     42, sessions:   1179, spiro:   1913, cols: 113
8 - SUBJECTS MORE THAN 6 SESSIONS pftType          subjects:     42, sessions:   1178, spiro:   1908, cols: 114
--- ADDING REGRESSION COLUMNS FOR MIN 3 SESSIONS PER SUBJ FOR EACH pftType PercPred

/home/ubuntu/git/eals_radcliff/eals_radcliff/utils/dataframes_paper.py:283: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_zephyrx["at_least_n_usable"] = df_zephyrx.groupby(["subject_id", "pftType"])[

--- REGRESSION COLUMNS COMPUTED                    subjects:     42, sessions:   1178, spiro:   1908, cols: 134

(2, 0, 42)

# Aural

In [ ]:
df_aural = load_aural_data()
print(f'N pALS: {df_aural.user_id.nunique()}, N sessions: {df_aural.session_id.nunique()}')
df_aural.head(2)

N pALS: 4, N sessions: 35

,user_id,sessionId,stepId,elicitType,stepCategory,stepData,startTime,endTime,status,promptListSize,promptType,name,sequenceNumber,uuid,s3Bucket,s3Path,s3AdaptiveWavPath,microphone,prompt,wav,path,relative_wav_path,date,session_id
0,8adba8d9-edd8-434c-b794-b2077322fc13,20250724-161109-A25609,10,speech,phonation,{},2025-07-24 21:13:33+00:00,2025-07-24T16:13:43-05:00,success,1,texts,secondPhonationRecordingOfThree,10,2d34effc-ae44-49e4-9454-f0e4a1a0decd,a2services-prod-sessionartifacts-everythingals...,8adba8d9-edd8-434c-b794-b2077322fc13/20250724-...,8adba8d9-edd8-434c-b794-b2077322fc13/20250724-...,BUILTIN_MIC,"Say ""aaah"" until your lungs are completely empty",10.wav,/data-output/s3_rapa/aural//8adba8d9-edd8-434c...,8adba8d9-edd8-434c-b794-b2077322fc13/20250724-...,2025-07-24,8adba8d9-edd8-434c-b794-b2077322fc13__2025-07-24
1,8adba8d9-edd8-434c-b794-b2077322fc13,20250724-161109-A25609,12,speech,phonation,{},2025-07-24 21:14:01+00:00,2025-07-24T16:14:10-05:00,success,1,texts,thirdPhonationRecordingOfThree,12,0dc7e4c8-a507-4074-bbd1-1daf70303e64,a2services-prod-sessionartifacts-everythingals...,8adba8d9-edd8-434c-b794-b2077322fc13/20250724-...,8adba8d9-edd8-434c-b794-b2077322fc13/20250724-...,BUILTIN_MIC,"Say ""aaah"" until your lungs are completely empty",12.wav,/data-output/s3_rapa/aural//8adba8d9-edd8-434c...,8adba8d9-edd8-434c-b794-b2077322fc13/20250724-...,2025-07-24,8adba8d9-edd8-434c-b794-b2077322fc13__2025-07-24