In [60]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [61]:
import pandas as pd; pd.set_option("display.max_columns", None)
import sys;sys.path.append("..")
from config import Paths
from dataframes import *
from eals_data.utils import venn_diagram
from eals_radcliff.utils import dataframes as radcliff_dataframes
from eals_radcliff.utils import dataframes_paper as radcliff_dataframes_paper

# ALSFRS-R

In [62]:
df_als = load_alsfrsr_data()
print(f'N pALS: {df_als.user_id.nunique()}, N sessions: {df_als.session_id.nunique()}')
df_als.head(2)

N pALS: 17, N sessions: 143

,speech,salvation,swallowing,handwriting,cutting_food_a,cutting_food_b,dressing_and_hygiene,turning_in_bed,walking,climbing_stairs,dyspnea,orthopnea,respiratory_insufficiency,ALS_total,created_at,user_id,date,bulbar_subscore,respiratory_subscore,fine_motor_subscore,gross_motor_subscore,session_id,months_since_first_session,years_since_first_session
0,4,4,4,3,3.0,NaN,3,3,3,1,4,3,4,39,2024-05-24 15:45:27+00:00,a07848cb-83b1-48ef-a314-ae5b5e5d448b,2024-05-24,12,11,NaN,7,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2024-05-24,0.0,0.0
1,4,4,4,3,2.0,4.0,2,3,2,1,4,0,2,31,2024-05-24 18:31:52+00:00,cee20458-8561-4496-932c-6855e6299641,2024-05-24,12,6,11.0,6,cee20458-8561-4496-932c-6855e6299641__2024-05-24,0.0,0.0

In [63]:
# Only one pALS in common between RAPA and Radcliff ALSFRS-R datasets

df_als_radcliff = radcliff_dataframes.load_alsfrsr_data()

venn_diagram(df_als.user_id.unique(), df_als_radcliff.user_id.unique())

(16, 1, 69)

# Demographics

In [64]:
df_demo = load_demographics_data()
print(f'N pALS: {df_demo.user_id.nunique()}, N sessions: {df_demo.session_id.nunique()}')
df_demo.head(2)

N pALS: 22, N sessions: 22

,user_id,family_disease_details,adhd_add,als,anxiety,bipolar_disorder,brain_aneurysm,Bulbar,c9orf_mutation,cancer,residence_location,birth_location,clinic_city,clinic_name,cognitive_impairment,concussions,Consent form signed Date,consent_signed,date_of_birth,date_of_diagnosis,symptom_onset_date,dementia,depression,diabetes,diagnosis,Do You Use The Railing When Climbing Stairs?,additional_conditions,current_cold,family_neuro_history,stairs_at_home,Do you use railing when climbing stairs?,epilepsy,ethnicity,hearing_loss,recent_hospitalization,speech_therapy,recent_quit_smoking,height_feet,height_inch,education_level,stairs_description,number_of_steps,english_first_language,symptom_onset_site_limb,marital_status,muscle_disease,No,birth_gender,specific_allergies,step_height,specified_dimensions,race,residence_type,residence_type_2,schizophrenia,symptom_onset_site,smoking_history,household_income,weight,current_prescriptions,stairs_flooring,dominant_hand,occupation,orthotics_type,study_shoes_type,us_region_identity,neurologist_physician_name,other_education,other language,other_symptoms,date,height_in_m,weight_in_kg,bmi,age,years_since_onset,session_id
0,1b0b349e-301f-46a4-a137-1fed70ca678d,None,No,Known ALS Gene,No,No,No,Swallowing,No,No,"Tustin, California",Mexico,Orange,UCI,No,No,None,Yes,1979-07-03,12/05/2024,2023-08-01,No,No,No,ALS,None,None of the above,No,None,None,None,No,"Mexican, Mexican American, Chicano/a",No,No,"yes, not currently",No,5.0,5.0,High School,None,None,No,None,Single,No,Spanish,Female,[],None,None,White,None,Condo/townhouse,No,Bulbar,I have never smoked,None,148.0,[],None,Right,"Disability, Not working at this time",[],None,West,Dr. Jeffery Mullen,None,None,None,2025-05-22,1.6510,67.131616,24.628216,46.0,1.806982,1b0b349e-301f-46a4-a137-1fed70ca678d__2025-05-22
1,1be5b39e-e8b8-47fc-9705-67849c71db69,None,No,None,Yes,No,No,Speech,No,No,"Chester, New Hampshire",Vietnam,"Boston, MA",MGH,No,No,None,None,1974-12-23,03/01/2023,2021-11-01,No,Yes,Yes,ALS,None,None of the above,"No, 10/21/2024",No,None,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,"No, 10/21/2024",No,No,5.0,2.0,Vocational Training,None,None,Yes,None,Married,No,None,Female,"[""Pollen"",""Dogs""]",None,None,Chinese,None,House,No,Bulbar,I have never smoked,None,130.0,"[""Claritin, PRN""]",None,Right,Account Manager,[],-,Northeast,Dr. Garret,None,None,None,2024-10-21,1.5748,58.966960,23.777048,50.0,2.970568,1be5b39e-e8b8-47fc-9705-67849c71db69__2024-10-21

In [65]:
# No pALS in common between RAPA and Radcliff Demographics datasets

df_demo_radcliff = radcliff_dataframes.load_demographics_data()

venn_diagram(df_demo.user_id.unique(), df_demo_radcliff.user_id.unique())

(22, 0, 78)

# ROADS

In [66]:
df_roads = load_roads_data()
print(f'N pALS: {df_roads.user_id.nunique()}, N sessions: {df_roads.session_id.nunique()}')
df_roads.head(2)

N pALS: 17, N sessions: 142

,nod_yes_and_no,ride_in_a_car,eat_soup,drink_milkshake,sit_on_toilet,swallow_pills,blow_out_candle,eat_dry_food,speak_on_phone,drink_out_of_glass,eat_large_meal,sign_nam_proper,get_into_bed,roll_over_in_bed,take_shower,use_knife_and_fork,walk_around_your_home,move_a_chair,speak_in_load_room,speak_for_hours,clip_nails,walk_up_1_flight_of_stairs,walk_up_a_hill,climb_a_stepstool,give_up_from_the_floor,carry_an_object_downstairs,stand_for_hours,get_heavy_objects_off_high_shelf,total,date_created,user_id,date,session_id
0,2,2,2,2,2,2,2,2,2,2,2,1,2,2,1,1,1,1,2,2,1,1,1,1,1,2,1,0,43,2024-05-24T15:48:59.000Z,a07848cb-83b1-48ef-a314-ae5b5e5d448b,2024-05-24,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2024-05-24
1,0,2,2,2,1,2,2,2,2,2,2,1,1,0,1,1,1,1,2,1,1,0,0,0,0,0,1,0,30,2024-05-24T18:36:07.000Z,cee20458-8561-4496-932c-6855e6299641,2024-05-24,cee20458-8561-4496-932c-6855e6299641__2024-05-24

# ZephyrX

In [67]:
df_zx = load_zephyrx_data(
    at_least_efforts_fvc_usable=0,
    keep_usable_sessions_only=False,
    at_least_months_in_study=0,
    at_least_n_sessions=0,
    multiply_by_100=False,
)
print(f'N pALS: {df_zx.user_id.nunique()}, N sessions: {df_zx.session_id.nunique()}')

1 - ORIGINAL DIMENSIONS:                           subjects:     13, sessions:    123, spiro:    288, cols: 108
--- KEEP SESSIONS THAT MAY NOT MET USABILITY CRITERIA (eals_usability column)
--- WARNING computing 'total_timespan' for each user after usability criteria: False
--- TOTAL TIMESPAN: min 0, max 545, mean 309.21
--- NOT FILTERING SUBJECTS BY MINIMUM MONTHS IN STUDY
--- NOT FILTERING SUBJECTS BY MINIMUM NUMBER OF SESSIONS
N pALS: 13, N sessions: 123

In [68]:
# # No pALS in common

# df_zx_radcliff = radcliff_dataframes_paper.load_zephyrx_data_paper()

# venn_diagram(df_zx.user_id.unique(), df_zx_radcliff.subject_id.unique())

# Aural

In [69]:
df_aural = load_aural_data(regenerate=True)
print(f'N pALS: {df_aural.user_id.nunique()}, N sessions: {df_aural.session_id.nunique()}')
df_aural.head(2)

Orginal aural dimensions: 89
Drop rows with no wav path: 1421
N pALS: 6, N sessions: 57

,user_id,sessionId,stepId,elicitType,stepCategory,stepData,startTime,endTime,status,promptListSize,promptType,name,sequenceNumber,uuid,s3Bucket,s3Path,s3AdaptiveWavPath,microphone,prompt,wav,path,relative_wav_path,date,session_id
0,a07848cb-83b1-48ef-a314-ae5b5e5d448b,20241010-132224-A73157,11,speech,phonation,{},2024-10-10 20:24:26+00:00,2024-10-10T13:24:48-07:00,success,1,texts,thirdPhonationRecordingOfThree,11,43abd992-dceb-4ccf-aab7-8ac25304364a,a2services-prod-sessionartifacts-everythingals...,a07848cb-83b1-48ef-a314-ae5b5e5d448b/20241010-...,a07848cb-83b1-48ef-a314-ae5b5e5d448b/20241010-...,BUILTIN_MIC,"Say ""aaah"" until your lungs are completely empty",11.wav,/home/ubuntu/git/data-output/s3_rapa/aural//a0...,a07848cb-83b1-48ef-a314-ae5b5e5d448b/20241010-...,2024-10-10,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2024-10-10
1,a07848cb-83b1-48ef-a314-ae5b5e5d448b,20241010-132224-A73157,13,speech,sentence,{},2024-10-10 20:24:53+00:00,2024-10-10T13:24:58-07:00,success,1,texts,12RotatingSentencesFixed1,13,e1c6b1ed-2f37-4c81-ab9f-8b46b567e9dc,a2services-prod-sessionartifacts-everythingals...,a07848cb-83b1-48ef-a314-ae5b5e5d448b/20241010-...,a07848cb-83b1-48ef-a314-ae5b5e5d448b/20241010-...,BUILTIN_MIC,The supermarket chain shut down because of poo...,13.wav,/home/ubuntu/git/data-output/s3_rapa/aural//a0...,a07848cb-83b1-48ef-a314-ae5b5e5d448b/20241010-...,2024-10-10,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2024-10-10