In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import re
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)  # Show all columns in DataFrame display
import sys; sys.path.append('..')
from config import Paths
from eals_targetals.utils import make_article_table
from dataframes import *

In [28]:
df_demo = load_demographics_data()

### RAPA pALS vs Radcliff pALS

In [4]:
import sys; sys.path.append('/home/ubuntu/eals/eals_radcliff_feli/')
from eals_radcliff.utils import dataframes

In [5]:
# Load radcliff demographics data
df_rad_demo = dataframes.load_demographics_data()

# add year_of_diagnosis and symptom_onset_year
df_rad_demo['symptom_onset_year'] = df_rad_demo.symptom_onset_date.dt.year
s = df_rad_demo['date_of_diagnosis'].astype(str).str.strip()
s = s.str.replace(r'(?i)^O(?=\d)', '0', regex=True) # Replace leading/embedded 'O' that should be a zero ->  O7/15/2023 -> 07/15/2023
s = s.str.replace(r'(?i)(?<=\d)O(?=\d)', '0', regex=True) # 1O/15/2023 -> 10/15/2023 (if it happens)
df_rad_demo['year_of_diagnosis'] = pd.to_datetime(s, format='%m/%d/%Y', errors='coerce').dt.year

# Load radcliff ALSFRSR data to get age at enrollment
df_rad_als = dataframes.load_alsfrsr_data()
df_rad_als.date = pd.to_datetime(df_rad_als.date)
df_rad_als.sort_values(['user_id','date'], inplace=True)
df_rad_als = df_rad_als.groupby('user_id').first().reset_index()

# Add age at enrollment
age_at_enrollment = []
for idx, row in df_rad_demo.iterrows():
    pal_als = df_rad_als.query('user_id == @row.user_id')
    if pal_als.shape[0] == 0:
        r = np.nan
    else:
        r = pal_als.date.iloc[0].year - row['date_of_birth'].year
    age_at_enrollment.append(r)
df_rad_demo["age_at_enrollment"] = age_at_enrollment

In [6]:
# Merge Radcliff and RAPA data
df_rad = pd.merge(df_rad_demo, df_rad_als, on='user_id', how='outer')
df_rad['study'] = 'Radcliff'
print(df_rad.shape)

df_rapa_als = load_alsfrsr_data()
df_rapa_als.date = pd.to_datetime(df_rapa_als.date)
df_rapa_als.sort_values(['user_id','date'], inplace=True)
df_rapa_als = df_rapa_als.groupby('user_id').first().reset_index()
df_rapa = df_demo.merge(df_rapa_als, on='user_id', how='outer')
df_rapa['study'] = 'RAPA'
print(df_rapa.shape)

df_comparison = pd.concat([df_rad, df_rapa], axis=0, ignore_index=True, sort=False)
print(df_comparison.shape)

(156, 97)
(22, 101)
(178, 107)

In [7]:
# Example usage
cat_columns = [
    'birth_gender',
    'symptom_onset_site',
    'specific_limb_onset', 
    'family_neuro_history',
    'muscle_disease',
    'has_fallen',
    'any_walking_aid',
    'anxiety', 
    'depression',
]
numeric_columns = [
    'age',
    'height_in_m',
    'bmi',
    'years_since_onset',
    'ALS_total',
    'speech',
    'salvation',
    'swallowing',
    'handwriting',
    'cutting_food_a',
    'cutting_food_b',
    'dressing_and_hygiene',
    'turning_in_bed',
    'walking',
    'climbing_stairs',
    'dyspnea',
    'orthopnea',
    'respiratory_insufficiency',
    'bulbar_subscore',
    'respiratory_subscore',
    'fine_motor_subscore',
    'gross_motor_subscore',

]

In [8]:
# This columns are not being compared in the table below
dis = []
for c in df_rapa.columns:
    if c not in cat_columns and c not in numeric_columns:
        dis.append(c)
df_rapa[dis].head(2)

,user_id,family_disease_details,adhd_add,als,bipolar_disorder,brain_aneurysm,Bulbar,c9orf_mutation,cancer,residence_location,birth_location,clinic_city,clinic_name,cognitive_impairment,concussions,Consent form signed Date,consent_signed,date_of_birth,date_of_diagnosis,symptom_onset_date,dementia,diabetes,diagnosis,Do You Use The Railing When Climbing Stairs?,additional_conditions,current_cold,stairs_at_home,Do you use railing when climbing stairs?,epilepsy,ethnicity,hearing_loss,recent_hospitalization,speech_therapy,recent_quit_smoking,height_feet,height_inch,education_level,stairs_description,number_of_steps,english_first_language,symptom_onset_site_limb,marital_status,No,specific_allergies,step_height,specified_dimensions,race,residence_type,residence_type_2,schizophrenia,smoking_history,household_income,weight,current_prescriptions,stairs_flooring,dominant_hand,occupation,orthotics_type,study_shoes_type,us_region_identity,neurologist_physician_name,other_education,other language,other_symptoms,date_x,weight_in_kg,session_id_x,created_at,date_y,session_id_y,months_since_first_session,years_since_first_session,study
0,1b0b349e-301f-46a4-a137-1fed70ca678d,None,No,Known ALS Gene,No,No,Swallowing,No,No,"Tustin, California",Mexico,Orange,UCI,No,No,None,Yes,1979-07-03,12/05/2024,2023-08-01,No,No,ALS,None,None of the above,No,None,None,No,"Mexican, Mexican American, Chicano/a",No,No,"yes, not currently",No,5.0,5.0,High School,None,None,No,None,Single,Spanish,[],None,None,White,None,Condo/townhouse,No,I have never smoked,None,148.0,[],None,Right,"Disability, Not working at this time",[],None,West,Dr. Jeffery Mullen,None,None,None,2025-05-22,67.131616,1b0b349e-301f-46a4-a137-1fed70ca678d__2025-05-22,2025-07-10 21:11:01+00:00,2025-07-10,1b0b349e-301f-46a4-a137-1fed70ca678d__2025-07-10,0.0,0.0,RAPA
1,1be5b39e-e8b8-47fc-9705-67849c71db69,None,No,None,No,No,Speech,No,No,"Chester, New Hampshire",Vietnam,"Boston, MA",MGH,No,No,None,None,1974-12-23,03/01/2023,2021-11-01,No,Yes,ALS,None,None of the above,"No, 10/21/2024",None,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,"No, 10/21/2024",No,No,5.0,2.0,Vocational Training,None,None,Yes,None,Married,None,"[""Pollen"",""Dogs""]",None,None,Chinese,None,House,No,I have never smoked,None,130.0,"[""Claritin, PRN""]",None,Right,Account Manager,[],-,Northeast,Dr. Garret,None,None,None,2024-10-21,58.966960,1be5b39e-e8b8-47fc-9705-67849c71db69__2024-10-21,NaT,NaT,NaN,NaN,NaN,RAPA

In [9]:
styled_table = make_article_table(df_comparison, 'study', [], numeric_columns, dec=2, p_dec=2)
display(styled_table)

In [10]:
styled_table = make_article_table(df_comparison, 'study', cat_columns, [], dec=2, p_dec=2)
display(styled_table)

Exact FFH not available. Falling back to chi-square p-value. Install 'fisher' for exact.

In [20]:
available = [c for c in cat_columns if c in df_comparison.columns]
df_comparison.query('study=="RAPA"')[available].info()

<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, 156 to 177
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   birth_gender          20 non-null     object
 1   symptom_onset_site    20 non-null     object
 2   family_neuro_history  19 non-null     object
 3   muscle_disease        20 non-null     object
 4   anxiety               20 non-null     object
 5   depression            20 non-null     object
dtypes: object(6)
memory usage: 1.2+ KB

In [27]:
sus = ['b45d5623-dc50-4529-bf2c-dc45bc22c0b4', 'b96c8a5b-8902-423a-8ced-18f6b01e9885']
df_comparison.query('user_id in @sus')

,user_id,family_disease_details,adhd_add,als,anxiety,bipolar_disorder,brain_aneurysm,Bulbar,c9orf_mutation,cancer,residence_location,birth_location,clinic_city,clinic_name,cognitive_impairment,concussions,consent_signed,Consent form signed?--Feb 2024,date_of_birth,date_of_diagnosis,symptom_onset_date,dementia,depression,diabetes,diagnosis,additional_conditions,current_cold,family_neuro_history,stairs_at_home,epilepsy,ethnicity,hearing_loss,recent_hospitalization,speech_therapy,recent_quit_smoking,height_feet,height_inch,education_level,stairs_description,number_of_steps,english_first_language,symptom_onset_site_limb,marital_status,muscle_disease,birth_gender,specific_allergies,step_height,specified_dimensions,race,residence_type_2,schizophrenia,symptom_onset_site,smoking_history,household_income,weight,current_prescriptions,stairs_flooring,dominant_hand,occupation,orthotics_type,study_shoes_type,us_region_identity,neurologist_physician_name,other_education,other_race,other_symptoms,date_x,height_in_m,weight_in_kg,bmi,age,years_since_onset,symptom_onset_year,year_of_diagnosis,age_at_enrollment,speech,salvation,swallowing,handwriting,cutting_food_a,cutting_food_b,dressing_and_hygiene,turning_in_bed,walking,climbing_stairs,dyspnea,orthopnea,respiratory_insufficiency,ALS_total,created_at,date_y,bulbar_subscore,respiratory_subscore,fine_motor_subscore,gross_motor_subscore,session_id,study,Consent form signed Date,Do You Use The Railing When Climbing Stairs?,Do you use railing when climbing stairs?,No,residence_type,other language,session_id_x,session_id_y,months_since_first_session,years_since_first_session
170,b45d5623-dc50-4529-bf2c-dc45bc22c0b4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,NaN,NaT,None,NaT,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,2026-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,RAPA,2026-01-19,None,None,None,None,None,b45d5623-dc50-4529-bf2c-dc45bc22c0b4__2026-01-19,NaN,NaN,NaN
171,b96c8a5b-8902-423a-8ced-18f6b01e9885,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,NaN,NaT,None,NaT,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,2025-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,3.0,2.0,NaN,2.0,2.0,2.0,0.0,1.0,1.0,4.0,26.0,2025-11-14 15:16:41+00:00,2025-11-14,9.0,6.0,NaN,4.0,NaN,RAPA,2025-11-14,None,None,None,None,None,b96c8a5b-8902-423a-8ced-18f6b01e9885__2025-11-14,b96c8a5b-8902-423a-8ced-18f6b01e9885__2025-11-14,0.0,0.0

In [25]:
df_comparison.query('study=="RAPA"')#]

,user_id,family_disease_details,adhd_add,als,anxiety,bipolar_disorder,brain_aneurysm,Bulbar,c9orf_mutation,cancer,residence_location,birth_location,clinic_city,clinic_name,cognitive_impairment,concussions,consent_signed,Consent form signed?--Feb 2024,date_of_birth,date_of_diagnosis,symptom_onset_date,dementia,depression,diabetes,diagnosis,additional_conditions,current_cold,family_neuro_history,stairs_at_home,epilepsy,ethnicity,hearing_loss,recent_hospitalization,speech_therapy,recent_quit_smoking,height_feet,height_inch,education_level,stairs_description,number_of_steps,english_first_language,symptom_onset_site_limb,marital_status,muscle_disease,birth_gender,specific_allergies,step_height,specified_dimensions,race,residence_type_2,schizophrenia,symptom_onset_site,smoking_history,household_income,weight,current_prescriptions,stairs_flooring,dominant_hand,occupation,orthotics_type,study_shoes_type,us_region_identity,neurologist_physician_name,other_education,other_race,other_symptoms,date_x,height_in_m,weight_in_kg,bmi,age,years_since_onset,symptom_onset_year,year_of_diagnosis,age_at_enrollment,speech,salvation,swallowing,handwriting,cutting_food_a,cutting_food_b,dressing_and_hygiene,turning_in_bed,walking,climbing_stairs,dyspnea,orthopnea,respiratory_insufficiency,ALS_total,created_at,date_y,bulbar_subscore,respiratory_subscore,fine_motor_subscore,gross_motor_subscore,session_id,study,Consent form signed Date,Do You Use The Railing When Climbing Stairs?,Do you use railing when climbing stairs?,No,residence_type,other language,session_id_x,session_id_y,months_since_first_session,years_since_first_session
156,1b0b349e-301f-46a4-a137-1fed70ca678d,None,No,Known ALS Gene,No,No,No,Swallowing,No,No,"Tustin, California",Mexico,Orange,UCI,No,No,Yes,NaN,1979-07-03,12/05/2024,2023-08-01,No,No,No,ALS,None of the above,No,None,None,No,"Mexican, Mexican American, Chicano/a",No,No,"yes, not currently",No,5.0,5.0,High School,None,None,No,None,Single,No,Female,[],None,None,White,Condo/townhouse,No,Bulbar,I have never smoked,None,148.0,[],None,Right,"Disability, Not working at this time",[],None,West,Dr. Jeffery Mullen,None,NaN,None,2025-05-22,1.6510,67.131616,24.628216,46.0,1.806982,NaN,NaN,NaN,2.0,2.0,3.0,3.0,1.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,29.0,2025-07-10 21:11:01+00:00,2025-07-10,7.0,7.0,8.0,9.0,NaN,RAPA,None,None,None,Spanish,None,None,1b0b349e-301f-46a4-a137-1fed70ca678d__2025-05-22,1b0b349e-301f-46a4-a137-1fed70ca678d__2025-07-10,0.0,0.0
157,1be5b39e-e8b8-47fc-9705-67849c71db69,None,No,None,Yes,No,No,Speech,No,No,"Chester, New Hampshire",Vietnam,"Boston, MA",MGH,No,No,None,NaN,1974-12-23,03/01/2023,2021-11-01,No,Yes,Yes,ALS,None of the above,"No, 10/21/2024",No,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,"No, 10/21/2024",No,No,5.0,2.0,Vocational Training,None,None,Yes,None,Married,No,Female,"[""Pollen"",""Dogs""]",None,None,Chinese,House,No,Bulbar,I have never smoked,None,130.0,"[""Claritin, PRN""]",None,Right,Account Manager,[],-,Northeast,Dr. Garret,None,NaN,None,2024-10-21,1.5748,58.966960,23.777048,50.0,2.970568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,RAPA,None,None,None,None,None,None,1be5b39e-e8b8-47fc-9705-67849c71db69__2024-10-21,NaN,NaN,NaN
158,623d5c97-db0b-41a5-aaac-9fd096ca3fa5,"Mother, 70, Dementia",Yes,Unsure,No,No,No,None,No,No,"Beaverton, OR","Hillsboro, OR","Providence, OR",Providence Neurological Eest,No,Yes,Yes,NaN,1966-07-21,04/24/2025,2024-10-01,No,Yes,Yes,ALS,Vision impaired / wear glasses,No,Yes,No,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,No,No,5.0,8.0,College,None,None,Yes,None,Single,No,Male,"[""Pollen, Grass""]",None,None,White,Condo/townhouse,No,Respiratory,I have never smoked,60000,178.0,[],None,Right,"Disability 2025, in I.T",[],None,West,Dt. Nicholas Olney,None,NaN,None,2025-11-11,1.7272,80.739376,27.064508,59.0,1.111567,NaN,NaN,NaN,3.0,3.0,4.0,2.0,3.0,3.0,4.0,4.0,4.0,2.0,3.0,2.0,2.0,36.0,2025-12-15 18:56:33+00:00,2025-12-15,10.0,7.0,12.0,10.0,NaN,RAPA,2025-12-15,None,None,None,None,None,623d5c97-db0b-41a5-aaac-9fd096ca3fa5__2025-11-11,623d5c97-db0b-41a5-aaac-9fd096ca3fa5__2025-12-15,0.0,0.0
159,68e9ff3b-749f-4217-8a3c-0028676ccbfa,None,No,None,Yes,Yes,Yes,None,No,Yes,State,City,Citywer,Teat2,Yes,Yes,Yes,NaN,1991-09-09,09/09/1989,1980-09-09,Yes,Yes,Yes,Any other Neurologic diagnosis,Hearing impaired / wear a hearing aid,No,No,Yes,Yes,"Not of Hispanic, Latino/a or Spanish origin",Yes,No,No,Yes,44.0,55.0,Doctorate,Spiral,994,Yes,Upper right Arm,Married,No,Male,[],881,556,White,House,No,Generalized,I have never smoked,44,77.0,[],Wood,Right,55,[],No,Midwest,Test1,None,NaN,None,2024-08-08,14.8082,34.926584,0.159276,33.0,43.912389,NaN,NaN,NaN,4.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,3.0,2.0,23.0,2024-08-08 10:02:29+00:00,2024-08-08,10.0,7.0,7.0,3.0,NaN,RAPA,None,"Yes, Both","Yes, Left",None,None,None,68e9ff3b-749f-4217-8a3c-0028676ccbfa__2024-08-08,68e9ff3b-749f-4217-8a3c-0028676ccbfa__2024-08-08,0.0,0.0
160,75f732c6-c4b2-46df-8757-868b847aa3b0,None,No,None,No,No,No,None,No,No,"Burke, Virginia","Tehran, Iran","Baltimore, MA",John's Hopkins,No,No,Yes,NaN,1957-04-02,05/10/2024,2023-08-01,No,No,No,ALS,None of the above,No,No,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,"Yes, 2months, 1x weekly",No,5.0,1.0,College,None,None,No,Upper right hand/finger,Married,No,Female,"[""Latex""]",None,None,Other Asian,House,No,Limb,I previously smoked,60000,116.0,"[""baclofin, 20mg, 2x daily, oral, peg"",""gabape...",None,Right,"Physicians Assistant, Retired, on Disability",[],None,South,Dr. Maragakis,None,NaN,None,2025-08-16,1.5494,52.616672,21.917765,68.0,2.042437,NaN,NaN,NaN,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,2.0,13.0,2025-09-05 20:06:06+00:00,2025-09-05,3.0,10.0,0.0,0.0,NaN,RAPA,None,None,None,Other,None,Farsi,75f732c6-c4b2-46df-8757-868b847aa3b0__2025-08-16,75f732c6-c4b2-46df-8757-868b847aa3b0__2025-09-05,0.0,0.0
161,78b12b30-b689-43d7-9604-5dea80c413f5,"Father, Dementia, 80",No,Known ALS Gene,No,No,No,None,Yes,No,"Mamarneck, New York","Bronx, New York",New Jersery,Hackensack- Maridiean Health,No,No,Yes,NaN,1969-07-07,06/01/2023,2022-12-09,No,No,Yes,ALS,Vision impaired / wear glasses,No,Yes,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,No,No,5.0,10.0,College,None,None,No,None,Married,No,Male,"[""N/A""]",None,None,White,House,No,Other site of symptoms,I previously smoked,,166.0,"[""Low dose Aspirin, 81 mg, daily, tab, oral "",...",None,Right,"Retired, Clerk Treasurer",[],None,Northeast,Dr. Robert Conners,None,NaN,"Fell on the left, from the right side trip, ri...",2025-07-08,1.7780,75.296272,23.818256,56.0,2.579055,NaN,NaN,NaN,1.0,4.0,4.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,4.0,4.0,4.0,23.0,2025-07-29 23:46:06+00:00,2025-07-29,9.0,12.0,0.0,2.0,NaN,RAPA,None,None,None,Other,None,"Italian, and Spanish",78b12b30-b689-43d7-9604-5dea80c413f5__2025-07-08,78b12b30-b689-43d7-9604-5dea80c413f5__2025-07-29,0.0,0.0
162,7ed30a17-32ec-4945-8598-1f08051e2e8d,"Paternal grandfathers sister, ALS, 80s",No,Unsure,Yes,No,No,None,No,No,"Maplewood, NJ","West Hartford, CT",New York,Columbia Hospital,No,Yes,Yes,NaN,1988-02-10,10/01/2013,2013-01-01,No,No,No,ALS,None of the above,No,Yes,No,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,No,None,5.0,5.0,Other,None,None,Yes,Lower right ankle/foot/toes,Single,No,Female,"[""N/A""]",None,None,White,House,No,Limb,I have never smoked,None,135.0,"[""Riluzole, start date: 2014"",""; Baclofin, dos...",None,Right,Not employed,[],None,Northeast,Dr. Jensy Andrews,JD,NaN,None,2025-02-25,1.6510,61.234920,22.464927,37.0,12.150582,NaN,NaN,NaN,2.0,3.0,2.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,4.0,2.0,3.0,22.0,2025-03-04 21:48:26+00:00,2025-03-04,7.0,9.0,0.0,6.0,NaN,RAPA,None,"No, do not use railing",None,None,None,None,7ed30a17-32ec-4945-8598-1f08051e2e8d__2025-02-25,7ed30a17-32ec-4945-8598-1f08051e2e8d__2025-03-04,0.0,0.0
163,8adba8d9-edd8-434c-b794-b2077322fc13,None,No,None,No,No,No,None,No,No,"Bertram, Texas","Austin, Texas",San Antonio,"UT Health,",No,No,Yes,NaN,2000-08-29,03/09/2023,2022-03-01,No,No,No,ALS,None of the above,No,No,None,No,"Mexican, Mexican American, Chicano/a",No,No,No,No,6.0,2.0,High School,None,None,Yes,Lower right ankle/foot/toes,Single,No,Male,"[""N/A""]",None,None,White,Mobile home,No,Limb,I have never smoked,40000,118.0,[],None,Right,Welder,[],None,South,Dr. Caroline Jackson,None,NaN,None,2025-06-26,1.8796,53.523856,15.150136,25.0,3.321013,NaN,NaN,NaN,3.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,2.0,16.0,2025-07-24 20:39:02+00:00,2025-07-24,9.0,7.0,0.0,0.0,NaN,RAPA,None,None,None,None,None,None,8adba8d9-edd8-434c-b794-b2077322fc13__2025-06-26,8adba8d9-edd8-434c-b794-b2077322fc13__2025-07-24,0.0,0.0
164,90e66a0a-eac4-4878-9005-5901f1c2900d,None,No,Unsure,Yes,No,No,None,No,No,"Ridgefield, CT","New York, New York","New York, New York",Columbia University,No,No,None,NaN,1958-09-19,03/01/2025,2024-03-01,No,No,No,ALS,None of the above,No,No,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,No,No,5.0,11.0,Doctorate,None,None,Yes,Upper right hand/finger,Married,No,Male,"[""Penicillin""]",None,None,White,House,No,Limb,I have never smoked,None,170.0,[],None,Right,"Retired, Orthopedic Surgeon",[],None,Northeast,Dr. Neal Schnider,None,NaN,None,2025-10-30,1.8034,77.110640,23.709925,67.0,1.664613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,RAPA,None,None,None,None,None,None,90e66a0a-eac4-4878-9005-5901f1c2900d__2025-10-30,NaN,NaN,NaN
165,9482e1ec-b2ca-444c-8a79-30dac3fb48f6,None,No,None,Yes,No,No,None,None,Yes,"Surprise, Arizona","Sacremento, California","Phoenix, AZ",Mayo Clinic,No,Yes,None,NaN,1953-09-09,03/01/2023,2022-07-01,No,Yes,No,ALS,Vision impaired / wear glasses,No,No,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,"Yes, G tube placed on 4/25/25 and hospitalized...",bo,None,5.0,7.0,College,None,None,Yes,Upper left hand/finger,Single,No,Female,"[""seasonal allergigies"",""EZ tape allergy"",""mox...",None,None,White,House,No,Limb,I have never smoked,None,178.0,[],None,Left,Clinical Research Coordinator,[],None,West,Dr. Stephen Johnson,None,NaN,None,2025-06-05,1.7018,80.739376,27.878432,72.0,2.929500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,RAPA,None,None,None,None,None,None,9482e1ec-b2ca-444c-8a79-30dac3fb48f6__2025-06-05,NaN,NaN,NaN
166,9485abe1-c1b5-4d27-8540-12b0f9807782,"Maternal Grandmother, AD, 66",No,None,Yes,No,No,None,No,No,"Grants Pass, Oregon","Whitefish, Montana","Portland, OR",Providence Neurological,No,Yes,Yes,NaN,1957-05-04,08/01/2022,2021-10-02,No,No,No,ALS,Vision impaired / wear glasses,No,Yes,Yes,No,"Not of Hispanic, Latino/a or Spanish origin","Not diagnosed, but suspects hearing loss","06/01, Phenomena",No,No,5.0,8.0,Doctorate,Straight,6,Yes,None,Single,No,Male,"[""Walnuts, Pecans ""]",None,None,White,House,No,Neck weakness,I have never smoked,24000,230.0,"[""Riluzole"",""Radicava"",""Matoprolol, 100mg, 2x ...",None,Right,Attorney,[],None,West,"Dr. Nicholas Olney, Dr. Tracy Bazan",None,NaN,None,2025-08-16,1.7272,104.326160,34.970993,68.0,3.871321,NaN,NaN,NaN,4.0,4.0,4.0,3.0,2.0,3.0,2.0,4.0,4.0,3.0,3.0,4.0,2.0,39.0,2025-09-04 22:34:29+00:00,2025-09-04,12.0,9.0,10.0,11.0,NaN,RAPA,None,"No, do not use railing",None,None,None,None,9485abe1-c1b5-4d27-8540-12b0f9807782__2025-08-16,9485abe1-c1b5-4d27-8540-12b0f9807782__2025-09-04,0.0,0.0
167,9c09639d-2956-4110-8f63-7aada0e25173,"Mother, Disease unknown but sure it was CNS",No,Known ALS Gene,Yes,No,No,None,Yes,Yes,"Attleboro, MA","Brockton, MA","Boston, MA",Mass General Hospital,No,No,Yes,NaN,1957-06-11,09/06/2022,2021-08-01,No,No,No,ALS,None of the above,No,Yes,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,No,No,5.0,11.0,College,None,None,Yes,Upper left hand/finger,Married,No,Male,"[""N/A""]",None,None,White,House,No,Limb,I have never smoked,70000,200.0,"[""Elequise, blood thinner, 10mg, daily (5mg 2x...",None,Right,"Retired, Contractor in Housing/Construction",[],None,Northeast,Dr. James Berry,None,NaN,None,2025-08-21,1.8034,90.718400,27.894029,68.0,4.054757,NaN,NaN,NaN,3.0,4.0,4.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,3.0,17.0,2025-09-10 14:09:47+00:00,2025-09-10,11.0,3.0,1.0,2.0,NaN,RAPA,None,None,None,None,None,None,9c09639d-2956-4110-8f63-7aada0e25173__2025-08-21,9c09639d-2956-4110-8f63-7aada0e25173__2025-09-10,0.0,0.0
168,a07848cb-83b1-48ef-a314-ae5b5e5d448b,"Grandmother, paternal 81",No,None,No,No,No,None,No,No,"Preston Hallow, New York","Rome, New York",None,Mass General Hospital,No,Yes,Yes,NaN,1966-03-06,03/06/2019,2017-09-01,No,Yes,No,ALS,None of the above,No,Yes,Yes,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,No,No,5.0,11.0,College,Straight,13,Yes,Lower left ankle/foot/toes,Married,No,Male,"[""Clyndomiycan ""]",9.25,None,White,House,No,Limb,I have never smoked,80000,185.0,[],Wood,Right,"Retired, General Contractor","[""AFO, carbon fiber ""]","Running sneakers, nike",Northeast,Dr. Merit Cuvkowizc,None,NaN,None,2024-05-13,1.8034,83.914520,25.801977,58.0,6.696783,NaN,NaN,NaN,4.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,4.0,3.0,4.0,39.0,2024-05-24 15:45:27+00:00,2024-05-24,12.0,11.0,12.0,7.0,NaN,RAPA,None,"Yes, Both",None,None,None,None,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2024-05-13,a07848cb-83b1-48ef-a314-ae5b5e5d448b__2024-05-24,0.0,0.0
169,a1568d21-c1f4-447c-8a4d-3565003d4773,"Father, ALS, 68",No,Known ALS Gene,No,No,No,Speech,Yes,No,"Middlesex, New Jersey","Bayonne, New Jersey",New Brunswick,Robert Wood Johnson,No,No,Yes,NaN,1961-10-01,02/27/2024,2023-05-01,No,No,No,ALS,None of the above,Yes,Yes,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,"Yes, but not enrolled now",None,5.0,4.0,College,None,None,Yes,None,Married,No,Female,[],None,None,White,None,No,Bulbar,I have never smoked,160000,112.0,"[""Riluzole"",""Radicava "",""Glycopyrolate "",""Nude...",None,Right,Retired,[],None,Northeast,Dr. Weng,None,NaN,None,2025-05-15,1.6256,50.802304,19.224543,64.0,2.039699,NaN,NaN,NaN,0.0,2.0,1.0,4.0,4.0,4.0,2.0,3.0,2.0,0.0,4.0,4.0,4.0,30.0,2025-05-22 19:06:58+00:00,2025-05-22,3.0,12.0,14.0,5.0,NaN,RAPA,None,None,None,None,House,None,a1568d21-c1f4-447c-8a4d-3565003d4773__2025-05-15,a1568d21-c1f4-447c-8a4d-3565003d4773__2025-05-22,0.0,0.0
170,b45d5623-dc50-4529-bf2c-dc45bc22c0b4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,NaN,NaT,None,NaT,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,2026-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,RAPA,2026-01-19,None,None,None,None,None,b45d5623-dc50-4529-bf2c-dc45bc22c0b4__2026-01-19,NaN,NaN,NaN
171,b96c8a5b-8902-423a-8ced-18f6b01e9885,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,NaN,NaT,None,NaT,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,2025-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,3.0,2.0,NaN,2.0,2.0,2.0,0.0,1.0,1.0,4.0,26.0,2025-11-14 15:16:41+00:00,2025-11-14,9.0,6.0,NaN,4.0,NaN,RAPA,2025-11-14,None,None,None,None,None,b96c8a5b-8902-423a-8ced-18f6b01e9885__2025-11-14,b96c8a5b-8902-423a-8ced-18f6b01e9885__2025-11-14,0.0,0.0
172,c2cc4d94-b103-407a-86f4-fb707b385a82,None,No,None,No,No,No,None,No,None,"Marlborough, New Hampshire","Freeport, New York","Boston, MA",Mass General Hospital,No,No,Yes,NaN,1958-12-26,04/29/2024,2023-05-01,No,No,No,ALS,Hearing impaired / wear a hearing aid,No,No,None,No,"Not of Hispanic, Latino/a or Spanish origin","Yes, acustic nerona",No,"Goes right now, every three months, going for ...",None,5.0,3.0,College,None,None,Yes,Lower right leg,Married,No,Female,"[""Sulfa, Levoquine ""]",None,None,White,House,No,Limb,I have never smoked,80000,155.0,[],None,Right,"Retired, Medical Office Managment",[],None,Northeast,Dr. James Berry,None,NaN,None,2025-05-14,1.6002,70.306760,27.456714,67.0,2.036961,NaN,NaN,NaN,0.0,2.0,3.0,3.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,3.0,24.0,2025-05-28 15:09:56+00:00,2025-05-28,5.0,7.0,NaN,5.0,NaN,RAPA,None,None,None,None,None,None,c2cc4d94-b103-407a-86f4-fb707b385a82__2025-05-14,c2cc4d94-b103-407a-86f4-fb707b385a82__2025-05-28,0.0,0.0
173,ca0d5d71-4c18-45e7-8c04-81feb7695e24,"Father, Parkinson's, approx 80yo; Mother, Altz...",No,None,No,No,No,None,No,No,"Canton, MA","Westbury, New York","Boston, MA","Mass General Hospital, MA",No,No,Yes,NaN,1970-01-05,06/10/2023,2022-10-01,No,No,No,ALS,None of the above,"No, 10/21/2024",Yes,Yes,No,"Not of Hispanic, Latino/a or Spanish origin",No,"No, 10/21/2024",No,No,5.0,11.0,College,None,None,Yes,Lower right ankle/foot/toes,Married,No,Male,"[""N/A""]",None,None,White,House,No,Limb,I have never smoked,200000,193.0,"[""Clonazepam, 1mg, 2x, oral tab, start date: 2...",None,Left,Retired,[],None,Northeast,Dr. Sabrina Paginona,None,NaN,None,2024-10-21,1.8034,87.543256,26.917738,54.0,2.056126,NaN,NaN,NaN,4.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,13.0,2024-11-05 19:11:07+00:00,2024-11-05,12.0,1.0,0.0,0.0,NaN,RAPA,None,None,None,None,None,None,ca0d5d71-4c18-45e7-8c04-81feb7695e24__2024-10-21,ca0d5d71-4c18-45e7-8c04-81feb7695e24__2024-11-05,0.0,0.0
174,cee20458-8561-4496-932c-6855e6299641,None,No,None,Yes,None,No,None,No,No,"Pembrook, MA","Boston, MA","Boston, MA",Mass General,No,No,Yes,NaN,1956-04-15,05/23/2023,NaT,No,Yes,Yes,ALS,None of the above,No,No,Yes,No,"Not of Hispanic, Latino/a or Spanish origin",No,No,"Yes, voice banking, one time occurance",No,5.0,8.0,College,Straight,14,Yes,Upper right Arm,Married,No,Female,[],8,None,Chinese,House,No,Limb,I have never smoked,None,146.0,"[""cyclobenoprene, muscle relaxant, dose: 5 mg,...",Wood,Right,Retired,"[""Neck brace ""]",sneakers- new balance,Northeast,Dr. Reda,None,NaN,None,2024-05-22,1.7272,66.224432,22.198978,68.0,NaN,NaN,NaN,NaN,4.0,4.0,4.0,3.0,2.0,4.0,2.0,3.0,2.0,1.0,4.0,0.0,2.0,31.0,2024-05-24 18:31:52+00:00,2024-05-24,12.0,6.0,11.0,6.0,NaN,RAPA,None,"Yes, Both",None,None,None,None,cee20458-8561-4496-932c-6855e6299641__2024-05-22,cee20458-8561-4496-932c-6855e6299641__2024-05-24,0.0,0.0
175,dfa70c88-ae38-48f9-b43d-58af77e6af64,None,No,None,Yes,No,No,None,No,Yes,"Massapequa, New York","Brooklyn, New York","Long Island, New York","Stoneybrook, Long Island, New York",No,No,None,NaN,1956-03-11,04/01/2024,2021-07-01,No,No,No,ALS,Vision impaired / wear glasses,None,No,None,No,"Not of Hispanic, Latino/a or Spanish origin",No,None,"Yes, goes to speech therapist but not any majo...",No,5.0,7.0,Other,None,None,Yes,Lower left leg,Married,No,Male,"[""Sulfa meds, penicillin, shrimp""]",None,None,White,House,No,Limb,I previously smoked,None,130.0,[],None,Right,Lawyer,[],None,Northeast,Dr. Samona Treidler,JD,NaN,None,2025-07-28,1.7018,58.966960,20.360653,69.0,4.073922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,RAPA,None,None,None,None,None,None,dfa70c88-ae38-48f9-b43d-58af77e6af64__2025-07-28,NaN,NaN,NaN